version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto11
  build:
    commands:
      - mvn clean package
  post_build:
    commands:
      - mv target/*.jar application.jar
      - mv deployment/appspec.yml appspec.yml
reports:
  UnitTests:
    files:
      - 'target/surefire-reports/TEST*.xml'
  CoverageReport:
    files:
      - 'target/site/jacoco/jacoco.xml'
    file-format: 'JACOCOXML'
cache:
  paths:
    - '/root/.m2/**/*'
artifacts:
  files:
    - application.jar
    - appspec.yml
    - 'deployment/**/*'