Parameters:
  ApplicationName:
    Type: String
    Description: Application Name
  StagingVPCCIDR:
    Type: String
    Description: CIDR block used to create the VPC (e.g. 10.0.0.0/24)
    AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{2})"
    ConstraintDescription: Must be a valid IP CIDR range of the form x.x.x.x/x. (e.g. 10.0.0.0/24)
  StagingPublicSubnet1CIDR:
    Type: String
    Description: CIDR block should used to create the public subnet in AZ1 (e.g. 10.0.0.0/26)
    AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{2})"
    ConstraintDescription: Must be a valid IP CIDR range of the form x.x.x.x/x. (e.g. 10.0.0.0/26)
  StagingPublicSubnet2CIDR:
    Type: String
    Description: CIDR block should used to create the public subnet in AZ2 (e.g. 10.0.0.64/26)
    AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{2})"
    ConstraintDescription: Must be a valid IP CIDR range of the form x.x.x.x/x. (e.g. 10.0.0.64/26)
  StagingPrivateSubnet1CIDR:
    Type: String
    Description: CIDR block should used to create the private subnet in AZ1 (e.g. 10.0.0.128/26)
    AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{2})"
    ConstraintDescription: Must be a valid IP CIDR range of the form x.x.x.x/x. (e.g. 10.0.0.128/26)
  StagingPrivateSubnet2CIDR:
    Type: String
    Description: CIDR block should used to create the private subnet in AZ2 (e.g. 10.0.0.192/26)
    AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{2})"
    ConstraintDescription: Must be a valid IP CIDR range of the form x.x.x.x/x. (e.g. 10.0.0.192/26)
  StagingApplicationInstanceType:
    Type: String
    Description: Instance Type
  ApplicationPort:
    Type: Number
    Description: Application Port
  LoadBalancerPort:
    Type: Number
    Description: Load Balancer Port
  BaseAmiId:
    Type: AWS::EC2::Image::Id
    Description: Ami Id
  UserDataBase64:
    Type: String
    Description: User Data Base64
  SshKeyName:
    Type: String
    Description: SSH Key Pair Name
  StagingLoadBalancerDeregistrationDelay:
    Type: Number
    Description: Load Balancer Deregistration Delay
  StagingHealthCheckIntervalSeconds:
    Type: Number
    Description: Staging Health Check Interval Seconds
  StagingHealthyThresholdCount:
    Type: Number
    Description: Staging Healthy Threshold Count
  StagingUnhealthyThresholdCount:
    Type: Number
    Description: Staging Unhealthy Threshold Count
Resources:
  StagingNetwork:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: 'network/network.yml'
      Parameters:
        VPCCIDR:
          Ref: StagingVPCCIDR
        PublicSubnet1CIDR:
          Ref: StagingPublicSubnet1CIDR
        PublicSubnet2CIDR:
          Ref: StagingPublicSubnet2CIDR
        PrivateSubnet1CIDR:
          Ref: StagingPrivateSubnet1CIDR
        PrivateSubnet2CIDR:
          Ref: StagingPrivateSubnet2CIDR
        ApplicationName:
          Ref: ApplicationName
        Environment: 'staging'
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}/StagingNetwork'
  StagingBastionHost:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: 'bastion-host/bastion-host.yml'
      Parameters:
        VpcId: !GetAtt StagingNetwork.Outputs.VPC
        SubnetId: !GetAtt StagingNetwork.Outputs.PublicSubnet1
        Environment: 'staging'
        AmiId:
          Ref: BaseAmiId
        SshKeyName:
          Ref: SshKeyName
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}::BastionHost'
  EC2BasedInfra:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: 'ec2-deployment/ec2-deployment.yml'
      Parameters:
        ApplicationName:
          Ref: ApplicationName
        Environment: 'staging'
        VpcId: !GetAtt StagingNetwork.Outputs.VPC
        PrivateSubnetIds: !GetAtt StagingNetwork.Outputs.PrivateSubnets
        PublicSubnetIds: !GetAtt StagingNetwork.Outputs.PublicSubnets
        ApplicationPort:
          Ref: ApplicationPort
        LoadBalancerPort:
          Ref: LoadBalancerPort
        AmiId:
          Ref: BaseAmiId
        InstanceType:
          Ref: StagingApplicationInstanceType
        UserDataBase64:
          Ref: UserDataBase64
        SshKeyName:
          Ref: SshKeyName
        BastionHostSecurityGroupId: !GetAtt StagingBastionHost.Outputs.SecurityGroupId
        LoadBalancerDeregistrationDelay:
          Ref: StagingLoadBalancerDeregistrationDelay
        HealthCheckIntervalSeconds:
          Ref: StagingHealthCheckIntervalSeconds
        HealthyThresholdCount:
          Ref: StagingHealthyThresholdCount
        UnhealthyThresholdCount:
          Ref: StagingUnhealthyThresholdCount
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}::EC2BasedInfra'
