version: 0.0
os: linux
files:
  - source: /deployment/application.service
    destination: /etc/systemd/system
  - source: /application.jar
    destination: /opt/application
file_exists_behavior: OVERWRITE
hooks:
  ApplicationStop:
    - location: deployment/scripts/stop_server.sh
      timeout: 10
      runas: root
  BeforeInstall:
    - location: deployment/scripts/before_install.sh
      timeout: 5
      runas: root
  ApplicationStart:
    - location: deployment/scripts/start_server.sh
      timeout: 60
      runas: root
  ValidateService:
    - location: deployment/scripts/validate_service.sh
      timeout: 20
      runas: root

